name: mf-server build
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CONTAINER_TAG: mf-server
  FILE_NAME: mf-server.cid

jobs:
  build:
    name: mf-server
    runs-on: [self-hosted, linux, X64]
    steps:
      - uses: actions/checkout@v3

      - name: reading running container id
        id: container-id
        run: |
          FILE="$HOME/docker-containers-id/$FILE_NAME"
          if [ -f "$FILE" ]; then
            ID=`cat $FILE`
            echo "id=$ID" >> $GITHUB_OUTPUT
          fi

      - name: copying essential files from container
        run: |
          DIR="$HOME/docker-buffer/$CONTAINER_TAG"
          if [ ! -z "${{steps.container-id.outputs.id}}" ]; then
            DIRECTORY_CHECK=`docker exec ${{steps.container-id.outputs.id}} [ -d /app/dist/microfrontends ] && echo 1 || echo 0`
            
            if [ "$DIRECTORY_CHECK" -eq 1 ]; then
              mkdir $DIR
              docker cp ${{steps.container-id.outputs.id}}:/app/dist/microfrontends "$DIR/"
            fi
          fi

      - name: stopping and removing container, deleting file
        run: |
          FILE="$HOME/docker-containers-id/$FILE_NAME"
          if [ ! -z "${{steps.container-id.outputs.id}}" ]; then
            rm $FILE
            docker stop ${{steps.container-id.outputs.id}}
            docker rm ${{steps.container-id.outputs.id}}
          fi

      - name: remove previous docker image
        run: docker rmi -f $CONTAINER_TAG

      - name: build docker image
        run: docker build . -t $CONTAINER_TAG

      - name: run docker container and save id
        run: |
          FILE="$HOME/docker-containers-id/$FILE_NAME"
          docker run --cidfile $FILE -d -p 3030:3030 $CONTAINER_TAG

      - name: copying essential files to container
        run: |
          DIR="$HOME/docker-buffer/$CONTAINER_TAG"
          if [ -d "$DIR" ]; then
            DIRECTORY_CHECK=`docker exec ${{steps.container-id.outputs.id}} [ -d /app/dist ] && echo 1 || echo 0`

            if [ "$DIRECTORY_CHECK" -eq 1 ]; then
              docker cp "$DIR/microfrontends" ${{steps.container-id.outputs.id}}:/app/dist/ 
              rm -r $DIR
            fi
          fi
